### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by xBalbinus** [FIL-Builders/filecoin-developer-console#2]
- Optimize SEO on landing page
- Fix installation instructions in Hero / CTA to what it should be on CLI, and also in the installation section.

https://github.com/FIL-Builders/create-fil-frame For more infos

- `Get started` header item should link to FIL-Frame GH's readme, button should anchor to correct installation instructions in the bottom
- FVM learn more link is broken, fix the link to point to docs' appropriate section. Same with smart contracts, proofs.
- The section with storage / retrieval integrations should be made clearer. The section should clearly indicate that these are protocols that we have quickstart kits for (and that's why they're listed on the site). Links should link to the proper branch.
- Fix repo name to something like filframe-landing
- Change logo to that of fil.builders page

**Comment by jbarnes850** [comment]
@xBalbinus Thanks for the feedback! See the PR with the revisions here: https://github.com/FIL-Builders/Fil-Frame-Landing-Page/pull/3
